# default.help
default.source = ['$HOME/.config/rphiic/colors.conf', 'all.conf'] # <uri-array>
# default.hi
default.boolr = true # <bool>
default.boolo = true # (bool)
default.vso = ['one', 'two'] # <string-array>
default.enumerator = nsfw # <sfw|nsfw|sketchy>
# default.enumerator2 = <sfw|nsfw|sketchy>
# default.enumerator33 = <sfw|nsfw|sketchy>
# default.enumerator444 = <sfw|nsfw|sketchy>
default.flag = sfw,sketchy # [sfw|nsfw|sketchy]
# default.subopt4.subopt3.subopt = <string>
# default.subopt4.subopt3.subopt2 = <string>
# default.subopt4.subopt2
# default.1111
# default.somerandom
# default.func = <int>

