# help
#source = [$HOME/.config/rphiic/colors.conf,all.conf] # <uri-array>
#source = $HOME/.config/rphiic/colors.conf
# hi
boolr = false # <bool>
boolo = true # (bool)
vso = ['one', 'two'] # <string-array>
enumerator = nsfw # <sfw|nsfw|sketchy>
# enumerator2 = <sfw|nsfw|sketchy>
# enumerator33 = <sfw|nsfw|sketchy>
# enumerator444 = <sfw|nsfw|sketchy>
flag = sfw,nsfw # [sfw|nsfw|sketchy]

rice.test.bg = rgb(febde3)
rice.test.fg = rgb(3ebde3)

# subopt4.subopt3.subopt = <string>
# subopt4.subopt3.subopt2 = <string>
# subopt4.subopt2
# 1111
# somerandom
#func = 123
#func = 456
# func = <int>
