[default]
source = [
  "all.conf",
  "~/.config/whvn/whvn.conf",
  "another/file/not/exists",
  "colors.conf"
] # <uri-array>
boolo = true # (bool)
name = "''" # <string>
vso = [
  "'one'",
  "'two'"
] # <string-array>
# vi = <int-array>
enumerator = nsfw # <sfw|nsfw|sketchy>
# enumerator2 = <sfw|nsfw|sketchy>
# enumerator33 = <sfw|nsfw|sketchy>
# enumerator444 = <sfw|nsfw|sketchy>
flag = sfw,sketchy # [sfw|nsfw|sketchy]
