
[rice.arg]

program.fg = rgb(ff0000)
program.bold = true

pos.fg = rgb(ff0000)
pos.it = true

short.fg = rgb(ff0000)
long.fg =  rgb(ff0000)
long.bold = true
env.bg =  rgb(ff0000)
env.fg =  rgb(010000)
env.bold = true
env.bold = true
desc.fg = rgb(ff0000)

group.fg = rgb(ff0000)
group.bold = true
group.ul = true
group-delim.fg = rgb(ff0000)

subopt.fg = gbr(0000ff)
subopt-delim.fg = rgb(ff0000)

enum.fg = rgb(ff0000)
enum-set.fg = rgb(ff0000)
enum-set.bold = true
enum-set.ul = true
enum-delim.fg = rgb(ff0000)

flag.fg = rgb(ff0000)
flag-set.fg = rgb(ff0000)
flag-set.bold = true
flag-set.ul = true
flag-delim.fg = rgb(ff0000)

hint.fg = rgb(ff0000)
hint-delim.fg = rgb(ff0000)

val.fg = rgb(ff0000)
val-delim.fg = rgb(ff0000)

