
[rice.arg]

program.fg = rgb(dd5555)
program.bold = true

pos.fg = rgb(aa55dd)
pos.it = true

short.fg = rgb(b97b97)
long.fg =  rgb(b97b97)
long.bold = true
env.bg =  rgb(865865)
env.fg =  rgb(010101)
env.bold = true
env.bold = true
desc.fg = rgb(aaaaaa)

group.fg = rgb(cccccc)
group.bold = true
group.ul = true
group-delim.fg = rgb(666666)

subopt.fg = gbr(66ee33)
subopt-delim.fg = rgb(666666)

enum.fg = rgb(5555bb)
enum-set.fg = rgb(7777dd)
enum-set.bold = true
enum-set.ul = true
enum-delim.fg = rgb(666666)

flag.fg = rgb(bbbb55)
flag-set.fg = rgb(dddd77)
flag-set.bold = true
flag-set.ul = true
flag-delim.fg = rgb(666666)

hint.fg = rgb(55aadd)
hint-delim.fg = rgb(666666)

val.fg = rgb(55dd55)
val-delim.fg = rgb(666666)

