[default]
source = [] # <uri-array>
sub = [lol, what, the, hell, is, this] # <string-array>

icons.lol = LOL!
icons.what = WHAT!
icons.the = THE!
icons.hell = HELL!
icons.is = IS!
icons.this = THIS!

